server:
  context-path: /seller
  port: 8082

logging:
  level:
    com.googlecode.jsonrpc4j: debug

rpc:
  client:
    url: http://localhost:8081/manager
    basePackage: com.imooc.api

spring:
  cache:
    type: hazelcast
  activemq:
      broker-url: tcp://192.168.0.100:61616
      packages:
#        所有包下的对象都是事件对象了
        trust-all: true
