server:
  context-path: /seller
  port: 8082

Logging:
  level:
    com.googlecode.jsonrpc4j: debug

rpc:
  client:
    url: http://localhost:8081/manager
    basePackage: com.imooc.api

spring:
  cache:
    type: hazelcast
  activemq:
      broker-url: tcp://192.168.0.100:61616
      packages:
#        所有包下的对象都是事件对象了
        trust-all: true
  datasource:
    url: jdbc:mysql://localhost:3306/seller?user=root&password=&useUnicode=true&characterEncoding=utf-8&useSSL=true
  jpa:
    show-sql: true

#swagger:
#  basePackage: com.imooc.seller.controller
#  title: 销售端API
#  description: >
#    authId 是由本方提供给接口调用方用于安全控制及身份识别，请在需要此参数的接口上，通过请求头传递。
#    sign 是接口调用方使用私钥对请求对象中的非空字段按字典排序之后的JSON字符串进行的签名。请在需要此参数的接口上，通过请求头传递。
