spring:
  jackson:
    data-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://localhost:3306/manager?user=root&password=&useUnicode=true&characterEncoding=utf-8&useSSL=true
  jpa:
    show-sql: true

server:
  context-path: /manager
  port: 8081

swagger:
  groupName: manager
  basePackage: com.imooc.manager.controller