spring:
  jackson:
    data-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://localhost:3306/manager?user=root&password=&useUnicode=true&characterEncoding=utf-8&useSSL=true
  jpa:
    show-sql: true
  activemq:
    broker-url: tcp://192.168.0.100:61616
  jms:
    pub-sub-domain: true

server:
  context-path: /manager
  port: 8084

swagger:
  groupName: manager
  basePackage: com.imooc.manager.controller